//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTris {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinTris.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à                                  @@@@@                                
        ///                          *@@@&amp;@@@@@@@@##@@@@                         
        ///                         @@@@@@@@@@@@@@@@@@@@@.                       
        ///         @             @@@@@@@@@@@@@@@@@@@@@@@@@            @@        
        ///       @@@@           @@@@@@@@@@@@@@@@@@@@@@@@@@@@          @@@@      
        ///     /@@@@@%        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@       @@@@@@     
        ///     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@    
        ///     @@@ [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Bowser {
            get {
                return ResourceManager.GetString("Bowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream bowserSound {
            get {
                return ResourceManager.GetStream("bowserSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream bowserSound2 {
            get {
                return ResourceManager.GetStream("bowserSound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à WIN.
        /// </summary>
        public static string cheat_code {
            get {
                return ResourceManager.GetString("cheat_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ??? : Tricheur !
        ///??? : Tu ne devais pas avoir accès à cette zone !
        ///??? : Maintenant il va falloir...
        ///payer !.
        /// </summary>
        public static string cheat_string {
            get {
                return ResourceManager.GetString("cheat_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  _____ _     _____     _     
        ///|  ___(_)_ _|_   _| __(_)___ 
        ///| |_  | | &apos;_ \| || &apos;__| / __|
        ///|  _| | | | | | || |  | \__ \
        ///|_|   |_|_| |_|_||_|  |_|___/.
        /// </summary>
        public static string fintris_title {
            get {
                return ResourceManager.GetString("fintris_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ╔═════════════╗
        ///║             ║
        ///║  Game Over  ║
        ///║             ║
        ///╚═════════════╝.
        /// </summary>
        public static string game_over {
            get {
                return ResourceManager.GetString("game_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à    ____       
        ///  / ___| ___  
        /// | |  _ / _ \ 
        /// | |_| | (_) |
        ///  \____|\___/.
        /// </summary>
        public static string go_title {
            get {
                return ResourceManager.GetString("go_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paused (Press P to unpause).
        /// </summary>
        public static string pause_text {
            get {
                return ResourceManager.GetString("pause_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à   ____                _       
        /// |  _ \ ___  __ _  __| |_   _ 
        /// | |_) / _ \/ _` |/ _` | | | |
        /// |  _ &lt;  __/ (_| | (_| | |_| |
        /// |_| \_\___|\__,_|\__,_|\__, |
        ///                        |___/.
        /// </summary>
        public static string ready_title {
            get {
                return ResourceManager.GetString("ready_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundCancel {
            get {
                return ResourceManager.GetStream("tetrisSoundCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream TetrisSoundFall {
            get {
                return ResourceManager.GetStream("TetrisSoundFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundGo {
            get {
                return ResourceManager.GetStream("tetrisSoundGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream TetrisSoundKo {
            get {
                return ResourceManager.GetStream("TetrisSoundKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundLvlUp {
            get {
                return ResourceManager.GetStream("tetrisSoundLvlUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundOK {
            get {
                return ResourceManager.GetStream("tetrisSoundOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream TetrisSoundPause {
            get {
                return ResourceManager.GetStream("TetrisSoundPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundReady {
            get {
                return ResourceManager.GetStream("tetrisSoundReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.IO.UnmanagedMemoryStream semblable à System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundTheme {
            get {
                return ResourceManager.GetStream("tetrisSoundTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please
        ///Try
        ///Again ❤.
        /// </summary>
        public static string try_again {
            get {
                return ResourceManager.GetString("try_again", resourceCulture);
            }
        }
    }
}
