//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTris {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinTris.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;                                   @                                  &quot;,
        ///&quot;                                 @@@@@                                &quot;,
        ///&quot;                          *@@@&amp;@@@@@@@@##@@@@                         &quot;,
        ///&quot;                         @@@@@@@@@@@@@@@@@@@@@.                       &quot;,
        ///&quot;         @             @@@@@@@@@@@@@@@@@@@@@@@@@            @@        &quot;,
        ///&quot;       @@@@           @@@@@@@@@@@@@@@@@@@@@@@@@@@@          @@@@      &quot;,
        ///&quot;     /@@@@@%        @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@       @@ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Bowser {
            get {
                return ResourceManager.GetString("Bowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream bowserSound {
            get {
                return ResourceManager.GetStream("bowserSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream bowserSound2 {
            get {
                return ResourceManager.GetStream("bowserSound2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  _____ _     _____     _     
        ///|  ___(_)_ _|_   _| __(_)___ 
        ///| |_  | | &apos;_ \| || &apos;__| / __|
        ///|  _| | | | | | || |  | \__ \
        ///|_|   |_|_| |_|_||_|  |_|___/.
        /// </summary>
        public static string fintris_title {
            get {
                return ResourceManager.GetString("fintris_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ╔═════════════╗
        ///║             ║
        ///║  Game Over  ║
        ///║             ║
        ///╚═════════════╝.
        /// </summary>
        public static string game_over {
            get {
                return ResourceManager.GetString("game_over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    ____       
        ///  / ___| ___  
        /// | |  _ / _ \ 
        /// | |_| | (_) |
        ///  \____|\___/.
        /// </summary>
        public static string go_title {
            get {
                return ResourceManager.GetString("go_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused (Press P to unpause).
        /// </summary>
        public static string pause_text {
            get {
                return ResourceManager.GetString("pause_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   ____                _       
        /// |  _ \ ___  __ _  __| |_   _ 
        /// | |_) / _ \/ _` |/ _` | | | |
        /// |  _ &lt;  __/ (_| | (_| | |_| |
        /// |_| \_\___|\__,_|\__,_|\__, |
        ///                        |___/.
        /// </summary>
        public static string ready_title {
            get {
                return ResourceManager.GetString("ready_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundCancel {
            get {
                return ResourceManager.GetStream("tetrisSoundCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream TetrisSoundFall {
            get {
                return ResourceManager.GetStream("TetrisSoundFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundGo {
            get {
                return ResourceManager.GetStream("tetrisSoundGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream TetrisSoundKo {
            get {
                return ResourceManager.GetStream("TetrisSoundKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundLvlUp {
            get {
                return ResourceManager.GetStream("tetrisSoundLvlUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundOK {
            get {
                return ResourceManager.GetStream("tetrisSoundOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream TetrisSoundPause {
            get {
                return ResourceManager.GetStream("TetrisSoundPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundReady {
            get {
                return ResourceManager.GetStream("tetrisSoundReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream tetrisSoundTheme {
            get {
                return ResourceManager.GetStream("tetrisSoundTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please
        ///Try
        ///Again ❤.
        /// </summary>
        public static string try_again {
            get {
                return ResourceManager.GetString("try_again", resourceCulture);
            }
        }
    }
}
